const db = require("../models");
const mongoose = require("mongoose");

async function getBaseTracks() {
	let userId = await db.User.find({}, { _id: 1 }).lean();
	let genreId = await db.Genre.find({}, { _id: 1 }).lean();
	return [
		{
			_id: "1",
			name: "Better of alone",
			// artist: "RXBYN",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644583924/tracks-dev/Rxbyn_-_better_off_alone_fvhwp8.mp3",
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644583757/tracks-thumbnails-dev/better_off_alone_gfmcby.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "20",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "2",
			name: "Alone",
			// artist: "Color Out",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644583929/tracks-dev/Color_Out_-_Alone_aw3gmk.mp3",
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644583757/tracks-thumbnails-dev/alone_rfib7a.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "21",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "3",
			name: "Mahidevran - Maze of sorrow",
			// artist: "MAHIDEVRAN ROCK BAND",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644583928/tracks-dev/Mahidevran_Rock_Band_-_Mahidevran_-_Maze_of_sorrow_ips3zs.mp3",
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644583757/tracks-thumbnails-dev/Maze_of_sorrow_r1crlr.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "22",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "4",
			name: "Aurora",
			// artist: 'Smoking with poets',
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644583928/tracks-dev/Smoking_With_Poets_-_to__Aurora_t2qnaw.mp3",
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644583757/tracks-thumbnails-dev/aurora_omys8y.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "8",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "5",
			name: "Sensitive",
			// artist: 'Infraction',
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644583922/tracks-dev/Infraction_-_Sensitive_vsu6qr.mp3",
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644583756/tracks-thumbnails-dev/Sensitive_unevif.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "3",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "6",
			name: "Tantalizing Youth",
			artist: "Social Square",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644583924/tracks-dev/Social_Square_-_Tantalizing_Youth_eykq87.mp3",
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644583757/tracks-thumbnails-dev/Tantalizing_Youth_bfshzo.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "2",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "7",
			name: "Igor Pumphonia - Point Of Light",
			artist: "Igor Pumphonia",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644584871/tracks-dev/Igor_Pumphonia_-_Igor_Pumphonia_-_Point_Of_Light_kjgbyz.mp3",
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644584802/tracks-thumbnails-dev/Igor_Pumphonia_-_Point_Of_Light_urg7nn.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "12",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "8",
			name: "Marsupial",
			artist: "Laurence Danova",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644584996/tracks-dev/Laurence_DaNova_-_Marsupial_1_bxvpkj.mp3",
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644585151/tracks-thumbnails-dev/Lurence_Danova_oeew0j.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "8",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "9",
			name: "Chasing Tomorrow (feat. Jade Gritty)",
			artist: "TAB",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644585238/tracks-dev/Tab_-_Chasing_Tomorrow__feat._Jade_Gritty__leh4r1.mp3",
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644585210/tracks-thumbnails-dev/TAB_fxakq3.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "12",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "10",
			name: "Healin My Blues",
			artist: "BJ Wilbanks",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644427496/tracks-thumbnails/thumbnail-1644427496210_qqpy4a.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644523019/tracks/track-1644523017728_qb6wq4.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "4",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "11",
			name: "Head Over Heels (Friend Group Remix)",
			artist: "The Devil Music Co.",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644585554/tracks-dev/The_Devil_Music_Co._-_Head_Over_Heels__Friend_Group_Remix__buotnt.mp3",
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644585551/tracks-thumbnails-dev/Head_Over_Heels_Friend_Group_Remix_c9uatt.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "21",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "12",
			name: "Under Water",
			artist: "THE.MADPIX.PROJECT",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644586422/tracks-dev/The.madpix.project_-_Under_Water_2_gyvrkl.mp3",
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644586423/tracks-thumbnails-dev/Under_Water_yoirsy.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "12",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "13",
			name: "Better",
			// artist: "A8",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644586627/tracks-dev/A8_MUSIC_PRODUCTIONS_-_Better_umwfkh.mp3",
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644586622/tracks-thumbnails-dev/A8_vxgyaf.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "3",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "14",
			name: "My Love",
			// artist: 'Modus',
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644586724/tracks-dev/MODUS_-_My_Love_z7tzk1.mp3",
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644586719/tracks-thumbnails-dev/My_love_wqjuiz.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "3",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "15",
			name: "Bebe go",
			// artist: 'P Steve Officiel',
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644586823/tracks-dev/P_Steve_Officiel_-_Bebe_go_r0hlbl.mp3",
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644586816/tracks-thumbnails-dev/bebe_go_zdfn6e.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "23",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "16",
			name: "Reflections (feat. Mathias Hagen)",
			// artist: 'KEVIN S.',
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644587062/tracks-dev/Kevin_S._-_Reflections__feat._Mathias_Hagen__lypkgw.mp3",
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644587058/tracks-thumbnails-dev/Reflections_qvdzan.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "24",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "17",
			name: "Un Ratito Nama (Prod: Duran The Coach)",
			// artist: 'Igor Pumphonia',
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644587219/tracks-dev/Lessky_-_Un_Ratito_Nama__Prod__Duran_The_Coach__npuws5.mp3",
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644587222/tracks-thumbnails-dev/Un_ratito_m2aeq0.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "23",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "18",
			name: "Sax Is My Cardio",
			// artist: 'KUZINMUZIN',
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644587961/tracks-dev/Kuzinmuzin_-_Sax_Is_My_Cardio_fqmvwb.mp3",
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644587960/tracks-thumbnails-dev/Sax_kgjfn8.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "5",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "19",
			name: "Chill Lofi Hip Hop Type Beat",
			// artist: 'PERYCREEP',
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644653754/tracks-dev/PeryCreep_-_Chill_Lofi_Hip_Hop_Type_Beat_l2k8zv.mp3",
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644653692/tracks-thumbnails-dev/Chill_Lofi_Hip_Hop_Type_Beat_ltpm24.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "25",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "20",
			name: "Monday 8am",
			// artist: 'KINEMATIC',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644602996/tracks-thumbnails-dev/Monday_8am_amfdta.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644602494/tracks-dev/D_JAY_KOI_-_We_got_the_vibes___Feat_Fil_Straughan__uz9qw7.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "6",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "21",
			name: "Boys, Girls, Toys & Words",
			// artist: 'MODERN PITCH',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644603153/tracks-thumbnails-dev/Boys_girls_toys_words_sxudby.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644603048/tracks-dev/Kinematic_-_Monday_8am_wpdupt.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "3",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "22",
			name: "HOUSE PARTY .(Feat Fil Straughan )",
			// artist: 'D JAY KOI',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644603313/tracks-thumbnails-dev/House_Party_iioyto.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644603319/tracks-dev/D_JAY_KOI_-_HOUSE_PARTY_._Feat_Fil_Straughan___moxvuy.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "25",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "23",
			name: "Healin My Blues",
			// artist: 'BJ Wilbanks',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644427496/tracks-thumbnails/thumbnail-1644427496210_qqpy4a.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644523019/tracks/track-1644523017728_qb6wq4.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "4",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "24",
			name: "Acidpowder",
			// artist: 'MAJED SALIH',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644611581/tracks-thumbnails-dev/acidpowder_mooqjz.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644611594/tracks-dev/Majed_Salih_-_Acidpowder_qpcwo0.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "12",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "26",
			name: "Talk it Out",
			// artist: 'SAMIE BOWER',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644611776/tracks-thumbnails-dev/Talk_it_Out_iqui41.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644611776/tracks-dev/Samie_Bower_-_Talk_It_Out_ekqoyc.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "4",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "27",
			name: "Hold me",
			// artist: 'POKKI DJ',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644611935/tracks-thumbnails-dev/Hold_me_eb28xg.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644611776/tracks-dev/Samie_Bower_-_Talk_It_Out_ekqoyc.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "18",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "28",
			name: "Work N' Play",
			// artist: 'SAMIE BOWER',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644612080/tracks-thumbnails-dev/Work_N_Play_rcn4gz.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644612079/tracks-dev/Samie_Bower_-_Work_N__Play_a148n3.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "27",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "29",
			name: "This Upbeat Hip-Hop",
			// artist: 'SAMIE BOWER',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644612266/tracks-thumbnails-dev/This_Upbeat_Hip-Hop_oinhwn.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644612272/tracks-dev/AVANT-BEATS_-_This_Upbeat_Hip-Hop_lu05ml.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "27",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "30",
			name: "volshebniki",
			// artist: 'KBKBTS.',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644612465/tracks-thumbnails-dev/Volshebniki_qqjjzn.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644612464/tracks-dev/kbkbts._-_volshebniki_ebpr8v.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "27",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "31",
			name: "Get it",
			// artist: 'ARCHANGEUR',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644612602/tracks-thumbnails-dev/Get_it_scljxk.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644612601/tracks-dev/Archangeur_-_GET_IT_1_swrra2.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "27",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "32",
			name: "Break The Ice",
			// artist: 'ADRAXX',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644612673/tracks-thumbnails-dev/Break_The_Ice_ye4fin.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644612673/tracks-dev/Adraxx_-_Break_The_Ice_1_zfeytu.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "27",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "33",
			name: "Typical",
			// artist: 'KELLEE MAIZE',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644612871/tracks-thumbnails-dev/In_Tune_kt1f6w.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644612796/tracks-dev/Tab_-_Typical_ej7thx.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "27",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "34",
			name: "Cold Inside",
			// artist: 'RUDE',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644612991/tracks-thumbnails-dev/Cold_Inside_y5irkj.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644612974/tracks-dev/Rude_-_Cold_Inside_vhhwbv.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "2",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "35",
			name: "Mourning Day",
			// artist: 'SADME',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644613158/tracks-thumbnails-dev/Mourning_Day_zevcgr.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644613157/tracks-dev/SadMe_-_Mourning_Day_h1nvyy.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "2",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "36",
			name: "Safe and Warm in Hunter's Arms",
			// artist: 'ROLLER GENOA',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644613311/tracks-thumbnails-dev/The_Edge_jfi0bd.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644613313/tracks-dev/Rising_Bones_-_The_Edge_y8hxwi.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "2",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "37",
			name: "Not My Problem",
			// artist: 'ALL MY FRIENDS HATE ME',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644613083/tracks-thumbnails-dev/Not_my_Problem_blr0wm.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644613082/tracks-dev/All_My_Friends_Hate_Me_-_Not_My_Problem_u2zmir.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "2",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "38",
			name: "The little robot",
			// artist: 'FORGET THE WHALE',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644613560/tracks-thumbnails-dev/The_little_robot_vd0ei4.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644613566/tracks-dev/Forget_the_Whale_-_The_Little_Robot_ul1rxl.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "2",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "39",
			name: "Im Growing Fangs",
			// artist: 'KELLEE MAIZE',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644613675/tracks-thumbnails-dev/Im_Growing_Fangs_r4rp25.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644613688/tracks-dev/Great_White_Buffalo_-_I_m_Growing_Fangs_gatqmx.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "2",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "40",
			name: "The Big Band Show",
			// artist: 'BODLEASONS',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644613819/tracks-thumbnails-dev/The_Big_Band_Show_oqmb9u.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644613779/tracks-dev/BoDleasons_-_The_Big_Band_Show_zcuzfn.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "15",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "41",
			name: "Blind girl (feat. Dia Yiannopoulou)",
			// artist: 'ZERO-PROJECT',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644613871/tracks-thumbnails-dev/Blind_girl_feat._Dia_Yiannopoulou_p0c4fi.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644613880/tracks-dev/zero-project_-_Blind_girl__feat._Dia_Yiannopoulou__yol7r7.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "15",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "42",
			name: "Sentimental Romantic Jazz",
			// artist: 'ZERO-PROJECT',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644613954/tracks-thumbnails-dev/Sentimental_Romantic_Jazz_rdeczl.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644613973/tracks-dev/Alexey_Anisimov_-_Sentimental_Romantic_Jazz_oka7lv.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "15",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "43",
			name: "day",
			// artist: 'NADEJDA DONEC',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644614087/tracks-thumbnails-dev/day_eq9bgb.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644614090/tracks-dev/Nadejda_Donec_-_day_olrwru.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "15",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "44",
			name: "Nothing (album v.)",
			// artist: 'NOSABE',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644614193/tracks-thumbnails-dev/Nothing_album_v._oyu7mt.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644614196/tracks-dev/Nosabe_-_Nothing__album_v.__o5wuwr.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "15",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "45",
			name: "А holiday romance",
			// artist: 'SERGO WIND',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644614259/tracks-thumbnails-dev/%D0%90_holiday_romance_prtlwt.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644614259/tracks-dev/Sergo_Wind_-___holiday_romance_tomkxt.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "15",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "46",
			name: "After Midnight",
			// artist: 'PAXTON PENNINGTON',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644614400/tracks-thumbnails-dev/After_Midnight_gqgxtw.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644614406/tracks-dev/Paxton_Pennington_-_After_Midnight_vpuyms.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "15",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "47",
			name: "Broken Record",
			// artist: 'KARA SQUARE AND PIERO PELUCHE',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644614400/tracks-thumbnails-dev/After_Midnight_gqgxtw.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644614548/tracks-dev/Kara_Square_and_Piero_Peluche_-_Broken_Record_cpqtd0.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "8",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "48",
			name: "Queen of Evening",
			// artist: 'KARA SQUARE AND PIERO PELUCHE',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644614565/tracks-thumbnails-dev/Queen_of_Evening_tf2h5p.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644614580/tracks-dev/Radio_Nowhere_-_Queen_of_Evening_nvltkt.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "8",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "49",
			name: "My Blues Tomorrow",
			// artist: 'THE VOW',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644614651/tracks-thumbnails-dev/My_Blues_Tomorrow_qiqq54.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644614651/tracks-dev/The_Vow_-_My_Blues_Tomorrow_e0wmbs.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "8",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "50",
			name: "time flies",
			// artist: 'THE VOW',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644614787/tracks-thumbnails-dev/time_flies_csbmnj.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644614788/tracks-dev/The_Happy_Somethings_-_time_flies_mbtbfn.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "8",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "51",
			name: "Rehash",
			// artist: 'MICHAEL ELLIS',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644614854/tracks-thumbnails-dev/Rehash_quufyk.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644614854/tracks-dev/Michael_Ellis_-_Rehash_fhditu.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "8",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "52",
			name: "shoestring",
			// artist: 'THE HAPPY SOMETHINGS',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644614962/tracks-thumbnails-dev/shoestring_nfply1.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644614953/tracks-dev/The_Happy_Somethings_-_shoestring_jwkgbb.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "8",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "53",
			name: "Legends",
			// artist: 'GALDSON',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644615101/tracks-thumbnails-dev/Legends_zgmewx.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644615102/tracks-dev/Galdson_-_Legends_a2agt8.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "10",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "54",
			name: "Sea Heart",
			// artist: 'GALDSON',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644615101/tracks-thumbnails-dev/Legends_zgmewx.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644615170/tracks-dev/Galdson_-_Sea_heart_1_p5orqc.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "10",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "55",
			name: "Beautiful Piano - full version",
			// artist: 'The White Cat',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644615187/tracks-thumbnails-dev/Beautiful_Piano_-_full_version_ppkyuy.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644615188/tracks-dev/WhiteCat_-_Beautiful_Piano_-_full_version_dvtbka.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "10",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "56",
			name: "J.S.Bach The Well-Tempered Clavier. Prelude 1, I Book",
			// artist: 'J.S.Bach',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644615287/tracks-thumbnails-dev/J.S.Bach_The_Well-Tempered_Clavier._Prelude_1_I_Book_u2pmrh.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644615286/tracks-dev/Madi%CC%80_-_Composer_-_J.S.Bach_The_Well-Tempered_Clavier._Prelude_1__I_Book_nrdoky.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "10",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "57",
			name: "Symphony No. 5 - Remastered",
			// artist: 'DANIEL BAUTISTA',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644615375/tracks-thumbnails-dev/Symphony_No._5_o3i6dx.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644615379/tracks-dev/Daniel_Bautista_-_Symphony_No._5_pwywfi.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "10",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "58",
			name: "Company (feat. Brittany D & Sam Mooney) (2021 24-bit Master)",
			// artist: 'COLE POWELL',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644615688/tracks-thumbnails-dev/Company_feat._Brittany_D_Sam_Mooney_2021_24-bit_Master_wgrd2b.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644615685/tracks-dev/Cole_Powell_-_Company__feat._Brittany_D__amp__Sam_Mooney___2021_24-bit_Master__bhxkkn.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "6",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "59",
			name: "Desert Gardens",
			// artist: 'KOSASH',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644615751/tracks-thumbnails-dev/Desert_Gardens_nvdueo.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644615722/tracks-dev/Kosash_-_Desert_Gardens_s9zzht.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "6",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "60",
			name: "Athens",
			// artist: 'PIERCE MURPHY',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644615790/tracks-thumbnails-dev/Athens_jzgrp1.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644615784/tracks-dev/Pierce_Murphy_-_Athens_ztvnfa.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "6",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "61",
			name: "Naturgemälde",
			// artist: 'TON',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644615857/tracks-thumbnails-dev/Naturgema%CC%88lde_o6tilm.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644615851/tracks-dev/Ton_-_Naturgema%CC%88lde_mpxz1j.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "6",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "62",
			name: "Fantasmas",
			// artist: 'TORTUGA DE MAR',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644615913/tracks-thumbnails-dev/Fantasmas_uxehmw.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644615913/tracks-dev/Tortuga_de_Mar_-_Fantasmas_sxxh7x.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "6",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "63",
			name: "Trouble With Love",
			// artist: 'RIVER BURN',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644615961/tracks-thumbnails-dev/Trouble_With_Love_zujdss.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644615961/tracks-dev/River_Burn_-_Trouble_With_Love_cviqcr.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "6",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "64",
			name: "I'll Wait",
			// artist: 'JONATHAN DIMMEL',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644616011/tracks-thumbnails-dev/I_ll_Wait_bgeotk.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644616010/tracks-dev/Jonathan_Dimmel_-_I_ll_Wait_m7dcok.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "6",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "65",
			name: "Unholy Roller",
			// artist: 'KILL CITY KILLS',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644616132/tracks-thumbnails-dev/Unholy_Roller_kepfw2.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644616133/tracks-dev/Kill_City_Kills_-_Unholy_Roller_qccgif.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "9",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "66",
			name: "Last Fight for the Championship",
			// artist: 'DOUBLE HILT',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644616198/tracks-thumbnails-dev/Last_Fight_for_the_Championship_qfenqu.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644616191/tracks-dev/Double_Hilt_-_Last_Fight_for_the_Championship_qaumoa.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "9",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "67",
			name: "Flux Amuck",
			// artist: 'Flux Amuck',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644616266/tracks-thumbnails-dev/Flux_Amuck_nevrlv.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644616260/tracks-dev/Flux_Amuck_-_Flux_Amuck_dl9xsf.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "9",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "68",
			name: "On The Edge",
			// artist: 'CARDINAL LINE',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644616327/tracks-thumbnails-dev/On_The_Edge_p2htlp.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644616327/tracks-dev/Cardinal_Line_-_On_The_Edge_mi1lu2.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "9",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "69",
			name: "The End of Time",
			// artist: 'OMAÏNEN',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644616402/tracks-thumbnails-dev/The_End_of_Time_mg9sbf.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644616414/tracks-dev/OMAI%CC%88NEN_-_The_End_of_Time_oinmce.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "9",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "70",
			name: "Scare In My Eyes",
			// artist: 'ABNORMAL CHANGES',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644616452/tracks-thumbnails-dev/Scare_In_My_Eyes_nkmwxl.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644616451/tracks-dev/Abnormal_changes_-_Scare_In_My_Eyes_imydg6.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "9",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "71",
			name: "Last Winter Day",
			// artist: 'AVENGER KILLS',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644616518/tracks-thumbnails-dev/Last_Winter_Day_qrmw7l.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644616511/tracks-dev/Avenger_Kills_-_Last_Winter_Day_nsfksz.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "9",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "72",
			name: "The End Has Come",
			// artist: 'AVENGER KILLS',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644616518/tracks-thumbnails-dev/Last_Winter_Day_qrmw7l.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644616581/tracks-dev/Avenger_Kills_-_The_End_Has_Come_t9r9np.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "9",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "73",
			name: "Jump Da Fuck Up",
			// artist: 'RUSTY TEA MAKERS',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644616614/tracks-thumbnails-dev/Jump_Da_Fuck_Up_vguvnf.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644616607/tracks-dev/Rusty_Tea_Makers_-_Jump_Da_Fuck_Up_lvworr.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "9",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "74",
			name: "Money feat. Fabio",
			// artist: 'DOCTOR FROST',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644616825/tracks-thumbnails-dev/Money_feat._Fabio_vttfcx.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644616812/tracks-dev/Doctor_Frost_-_Money_feat._Fabio_nprr98.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "28",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "75",
			name: "Wrong Concept",
			// artist: 'MOON I MEAN',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644616886/tracks-thumbnails-dev/Wrong_Concept_ljvi4r.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644616881/tracks-dev/Moon_I_Mean_-_Wrong_Concept_ed8hi1.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "28",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "76",
			name: "Freedom",
			// artist: 'MAMA SUN SYSTEM',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644616960/tracks-thumbnails-dev/Freedom_nxuhkq.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644616957/tracks-dev/Mama_Sun_System_-_Freedom_lybabn.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "28",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "77",
			name: "Contigo",
			// artist: 'LOS BRODIES',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644617027/tracks-thumbnails-dev/Contigo_rszueh.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644617033/tracks-dev/Los_Brodies_-_Contigo_ax1fus.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "28",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "78",
			name: "Tequilight",
			// artist: 'CHEWBASKA',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644617065/tracks-thumbnails-dev/Tequilight_jkwqsy.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644617065/tracks-dev/Chewbaska_-_Tequilight_scxgva.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "28",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "79",
			name: "Enough",
			// artist: 'MOON I MEAN',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644617158/tracks-thumbnails-dev/Enough_sqy5ya.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644617152/tracks-dev/Moon_I_Mean_-_Enough_qukuqv.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "28",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "80",
			name: "Melts Away",
			// artist: 'MICHAEL C. JONES',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644617302/tracks-thumbnails-dev/Melts_Away_arvhfe.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644617333/tracks-dev/Michael_C._Jones_-_Melts_Away_iuvypx.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "11",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "81",
			name: "ÑA ÑO MONGETATA",
			// artist: 'FRAN VILLALBA',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644617393/tracks-thumbnails-dev/N%CC%83A_N%CC%83O_MONGETATA_ni5wie.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644617363/tracks-dev/Fran_Villalba_-_N_A_N_O_MONGETATA_bafiae.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "11",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "82",
			name: "The imagined last day of Crawford Gordon",
			// artist: 'BETP5',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644617440/tracks-thumbnails-dev/The_imagined_last_day_of_Crawford_Gordon_szu57a.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644617434/tracks-dev/BETP5_-_The_imagined_last_day_of_Crawford_Gordon_mgylqe.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "11",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "83",
			name: "Luna Lupe",
			// artist: 'THE RABBITTS',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644617488/tracks-thumbnails-dev/Luna_Lupe_w9dyqu.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644617489/tracks-dev/The_Rabbitts_-_Luna_Lupe_x7kizm.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "11",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "84",
			name: "Holy lonely night",
			// artist: 'GROUND & LEAVES',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644617544/tracks-thumbnails-dev/Holy_lonely_night_ph7uy5.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644617544/tracks-dev/Ground__amp__Leaves_-_Holy_lonely_night_gmobgf.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "11",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "85",
			name: "The Scene of Your Crime",
			// artist: 'FUZZY LOGIC',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644617592/tracks-thumbnails-dev/The_Scene_of_Your_Crime_aaxwam.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644617587/tracks-dev/Fuzzy_Logic_-_The_Scene_of_Your_Crime_wdn3jp.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "11",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "86",
			name: "Vatewizer",
			// artist: 'MAJED SALIH',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644617760/tracks-thumbnails-dev/Vaterwizer_yrgodz.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644617764/tracks-dev/Majed_Salih_-_Vatewizer_dpstlc.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "29",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "87",
			name: "Pianodice",
			// artist: 'MAJED SALIH',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644617816/tracks-thumbnails-dev/Pianodice_c1jmcw.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644617812/tracks-dev/Majed_Salih_-_Pianodice_llwnbg.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "29",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "88",
			name: "Love And Energy",
			// artist: 'SEVENNOTES',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644617873/tracks-thumbnails-dev/Love_And_Energy_uodds2.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644617866/tracks-dev/Sevennotes_-_Love_And_Energy_dkcgvm.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "29",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "89",
			name: "Milmenomal",
			// artist: 'MAJED SALIH',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644617922/tracks-thumbnails-dev/Milmenomal_mo3hfb.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644617923/tracks-dev/Majed_Salih_-_Milmenomal_tp9gyi.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "29",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "90",
			name: "Restful",
			// artist: 'SOLXIS',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644617990/tracks-thumbnails-dev/Restful_zbavfg.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644617969/tracks-dev/Solxis_-_Restful_b4lys1.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "29",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "91",
			name: "The corn road",
			// artist: 'FLASHINMUSIC',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644623893/tracks-thumbnails-dev/The_corn_road_zn4kzw.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644623885/tracks-dev/Flashinmusic_-_The_corn_road_yvpak1.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "1",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "92",
			name: "Spirit Walk",
			// artist: 'THE MIND ORCHESTRA',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644623940/tracks-thumbnails-dev/Spirit_Walk_s6tfwr.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644623940/tracks-dev/The_Mind_Orchestra_-_Spirit_Walk_kh0exz.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "1",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "93",
			name: "See Me When I Shine",
			// artist: 'MICHAEL ELLIS',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644624020/tracks-thumbnails-dev/See_Me_When_I_Shine_rohqmf.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644624012/tracks-dev/Michael_Ellis_-_See_Me_When_I_Shine_kdk38d.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "1",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "94",
			name: "Old News",
			// artist: 'HOT FICTION',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644624077/tracks-thumbnails-dev/Old_News_iagtyk.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644624067/tracks-dev/Hot_Fiction_-_Old_News_ktv7co.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "1",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "95",
			name: "I Know Where You've Been",
			// artist: 'HOT FICTION',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644624077/tracks-thumbnails-dev/Old_News_iagtyk.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/image/upload/v1644624165/tracks-thumbnails-dev/I_Know_Where_You_ve_Been_whdmfq.jpg",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "1",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "96",
			name: "Passeggiata",
			// artist: 'PAOLO PAVAN PASQUALINO UBALDINI',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644624192/tracks-thumbnails-dev/Passeggiata_bdjadr.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644624185/tracks-dev/Paolo_Pavan_Pasqualino_Ubaldini_-_Passeggiata_fiwljr.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "1",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "97",
			name: "YENDRY MUNDIAL - ME MO VI",
			// artist: 'YENDRY Y LETANO',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644624332/tracks-thumbnails-dev/YENDRY_MUNDIAL_-_ME_MO_VI_vcsst8.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644624325/tracks-dev/yendry_y_letano_-_YENDRY_MUNDIAL_-_ME_MO_VI_hzrzjx.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "23",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "98",
			name: "Meter Rise",
			// artist: 'PNFA',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644624411/tracks-thumbnails-dev/Meter_Rise_ayucku.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644624389/tracks-dev/PNFA_-_Meter_Rise_hdxkjy.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "22",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "99",
			name: "Mil Noches",
			// artist: 'RIS CHARM',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644624514/tracks-thumbnails-dev/Mil_Noches_pnxmc2.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644624506/tracks-dev/Ris_Charm_-_Mil_Noches_ykas4f.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "3",
			likedBy: userId.map((user) => user._id),
		},
		{
			_id: "100",
			name: "Canto del ayer",
			// artist: 'RIS CHARM',
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			thumbnail:
				"https://res.cloudinary.com/dmkdsujzh/image/upload/v1644624617/tracks-thumbnails-dev/Canto_del_ayer_cfgepp.jpg",
			url: "https://res.cloudinary.com/dmkdsujzh/video/upload/v1644624506/tracks-dev/Ris_Charm_-_Mil_Noches_ykas4f.mp3",
			userId: userId[Math.ceil(Math.random() * userId.length) - 1]._id,
			genre: "3",
			likedBy: userId.map((user) => user._id),
		},
	];
}

module.exports = { getBaseTracks };
