const DEFAULT_PROFILE_IMAGE = "Image";
const DEFAULT_PLAYLIST_THUMBNAIL = "Link Image";

module.exports = {
	DEFAULT_PROFILE_IMAGE: DEFAULT_PROFILE_IMAGE,
	DEFAULT_PLAYLIST_THUMBNAIL: DEFAULT_PLAYLIST_THUMBNAIL,
};
