const DEFAULT_PROFILE_IMAGE = "link imagen";
const DEFAULT_PLAYLIST_THUMBNAIL = "link imagen";

module.exports = {
	DEFAULT_PROFILE_IMAGE: DEFAULT_PROFILE_IMAGE,
	DEFAULT_PLAYLIST_THUMBNAIL: DEFAULT_PLAYLIST_THUMBNAIL,
};
