const DEFAULT_PROFILE_IMAGE =
	"";
const DEFAULT_PLAYLIST_THUMBNAIL =
	"";

module.exports = {
	DEFAULT_PROFILE_IMAGE: DEFAULT_PROFILE_IMAGE,
	DEFAULT_PLAYLIST_THUMBNAIL: DEFAULT_PLAYLIST_THUMBNAIL,
};
